/*
 * This file is generated by jOOQ.
 */
package me.aa07.profilerdaemon.database;


import java.util.Arrays;
import java.util.List;

import me.aa07.profilerdaemon.database.tables.Procs;
import me.aa07.profilerdaemon.database.tables.Samples;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParadiseProfilerdaemon extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>paradise_profilerdaemon</code>
     */
    public static final ParadiseProfilerdaemon PARADISE_PROFILERDAEMON = new ParadiseProfilerdaemon();

    /**
     * The table <code>paradise_profilerdaemon.procs</code>.
     */
    public final Procs PROCS = Procs.PROCS;

    /**
     * The table <code>paradise_profilerdaemon.samples</code>.
     */
    public final Samples SAMPLES = Samples.SAMPLES;

    /**
     * No further instances allowed
     */
    private ParadiseProfilerdaemon() {
        super("paradise_profilerdaemon", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Procs.PROCS,
            Samples.SAMPLES
        );
    }
}
