/*
 * This file is generated by jOOQ.
 */
package me.aa07.profilerdaemon.database;


import me.aa07.profilerdaemon.database.tables.Procs;
import me.aa07.profilerdaemon.database.tables.Samples;


/**
 * Convenience access to all tables in paradise_profilerdaemon.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>paradise_profilerdaemon.procs</code>.
     */
    public static final Procs PROCS = Procs.PROCS;

    /**
     * The table <code>paradise_profilerdaemon.samples</code>.
     */
    public static final Samples SAMPLES = Samples.SAMPLES;
}
